#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    exclude = ["change_url"]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.username = "username"
    args.display_name = "name"
    args.summary = "summary"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    # test upgrade from 29ef86ea663d4d9e7079c861adb613eaabf7800f - v1 version of package
    test_upgrade_from.29ef86ea.name = "Upgrade from v1 version of package"
    test_upgrade_from.753249e7f7f1e232030215458ff864d0bfb173e7.name = "Upgrade from 2.0.0~ynh4"
