#!/bin/bash

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_print_info --message="Declaring files to be backed up..."

# Note that we don't backup Python/the venv as it can be easily rebuilt
ynh_backup --src_path="${microblogpub_app}"
ynh_backup --src_path="${data_dir}"
ynh_backup --src_path="${install_dir}/inv.sh"
ynh_backup --src_path="/etc/nginx/conf.d/${domain}.d/${app}.conf"
ynh_backup --src_path="/etc/fail2ban/jail.d/${app}.conf"
ynh_backup --src_path="/etc/fail2ban/filter.d/${app}.conf"
ynh_backup --src_path="/etc/logrotate.d/${app}"
ynh_backup --src_path="/etc/systemd/system/${app}.service"

ynh_print_info --message="Backup script completed for ${app}."
