#!/bin/bash
source _common.sh
source /usr/share/yunohost/helpers

# should'nt be necessary since it is set during each installation
# ynh_app_setting_set --key=python_version --value=$python_version

ynh_script_progression "Setting up source files..."
ynh_setup_source --dest_dir="${microblogpub_app}"

ynh_script_progression "moving ${microblogpub_app}/data dir to ${data_dir}..."
microblogpub_move_data

ynh_script_progression "Installing Python ${python_version}..."
microblogpub_install_python

ynh_script_progression "Installing Python deps..."
microblogpub_install_deps
# after installing the venv through poetry set the $microblogpub_active_venv to be used
# later to configure the systemd.service
microblogpub_set_active_venv

ynh_script_progression "Setting up microblogpub config..."
microblogpub_initial_setup

ynh_script_progression "Initializing database..."
microblogpub_initialize_db

ynh_script_progression "Configure integration version to show..."
microblogpub_set_version

ynh_script_progression "Generate wrapper vor pyenv..."
ynh_config_add --template="inv.sh" --destination="$install_dir/inv.sh"

ynh_script_progression "Configuring NGINX web server..."
ynh_config_add_nginx

ynh_script_progression "Configuring $app's systemd service..."
ynh_config_add_systemd

ynh_script_progression "Configuring log rotation..."
ynh_config_add_logrotate

ynh_script_progression "Configuring Fail2Ban..."
touch /var/log/$app/uvicorn.log
ynh_config_add_fail2ban --logpath="/var/log/$app/uvicorn.log" --failregex="INFO:.+ <HOST>:0 - \"POST /admin/login HTTP/.*\" 403 Forbidden"

ynh_script_progression "Integrating service in YunoHost..."
yunohost service add $app --description="A self-hosted, single-user, ActivityPub powered microblog." --log="/var/log/$app/$app.log"

ynh_script_progression "setting file permissions..."
microblogpub_set_filepermissions

ynh_script_progression "Starting $app's systemd service..."
# TODO look for string in logfile that confirms successful start
# put this into a function - it is used in other places also
ynh_systemctl --service=$app --action="start"

ynh_script_progression "Mark this as installed from the V2 app integration..."
ynh_app_setting_set --key='installed_from' --value='YunohostV2catalogVersion'

ynh_script_progression "Installation of $app completed"
