#!/bin/bash

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

# ynh_script_progression --message="Setting up python ${python_version}..." --weight=50
# microblogpub_install_python

ynh_script_progression --message="Restoring the app main directory..." --weight=50
ynh_restore_file --origin_path="${microblogpub_app}"

# ynh_script_progression --message="Installing dependencies..." --weight=50
# microblogpub_install_deps

ynh_script_progression --message="Restoring inv.sh..." --weight=50
ynh_restore_file --origin_path="${install_dir}/inv.sh"

ynh_script_progression --message="Restoring data..." --weight=50
ynh_restore_file --origin_path="${data_dir}"

# TODO backup logs with --big
# Re-create the logs dir
mkdir /var/log/$app
# Make fail2ban happy
touch /var/log/$app/uvicorn.log

ynh_script_progression --message="Setting file permsissions..." --weight=50
microblogpub_set_filepermissions

ynh_script_progression --message="Restoring the Fail2Ban configuration..." --weight=1
ynh_restore_file --origin_path="/etc/fail2ban/jail.d/$app.conf"
ynh_restore_file --origin_path="/etc/fail2ban/filter.d/$app.conf"
ynh_systemd_action --action=restart --service_name=fail2ban

ynh_script_progression --message="Restoring the NGINX web server configuration..." --weight=1
ynh_restore_file --origin_path="/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_script_progression --message="Restoring the systemd configuration..." --weight=1
ynh_restore_file --origin_path="/etc/systemd/system/$app.service"
systemctl enable $app.service --quiet

ynh_script_progression --message="Restoring the logrotate configuration..." --weight=1
ynh_restore_file --origin_path="/etc/logrotate.d/$app"

ynh_script_progression --message="Integrating service in YunoHost..." --weight=1
yunohost service add $app --description="A self-hosted, single-user, ActivityPub powered microblog." --log="/var/log/$app/$app.log"

ynh_script_progression --message="Starting a systemd service..." --weight=1
ynh_systemd_action --service_name=$app --action="start" --log_path="/var/log/$app/$app.log"

ynh_script_progression --message="Reloading NGINX web server..." --weight=1
ynh_systemd_action --service_name=nginx --action=reload

ynh_script_progression --message="Restoration completed for $app" --last
