#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source ../settings/scripts/ynh_python_install
source /usr/share/yunohost/helpers

ynh_python_install

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

#=================================================
# RESTORE THE DATA DIRECTORY
#=================================================
ynh_script_progression "Restoring the data directory..."

ynh_restore "$data_dir"

# TODO backup logs with --big
# Re-create the logs dir
mkdir -p /var/log/$app
# Make fail2ban happy
touch /var/log/$app/uvicorn.log

ynh_script_progression "Setting file permsissions..."
local dir
chmod 750 "$install_dir" "$data_dir"
chmod -R o-rwx "$install_dir" "$data_dir"
chown -R $app:www-data "$install_dir" "$data_dir"
chmod u+x $install_dir/inv.sh
chown -R $app:www-data "/var/log/$app"

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/systemd/system/$app.service"
systemctl enable "$app.service" --quiet

yunohost service add "$app" --description="A self-hosted, single-user, ActivityPub powered microblog." --log="/var/log/$app/$app.log"

ynh_restore "/etc/logrotate.d/$app"

ynh_restore "/etc/fail2ban/jail.d/$app.conf"
ynh_restore "/etc/fail2ban/filter.d/$app.conf"
ynh_systemctl --action=restart --service=fail2ban

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service="$app" --action="start"

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
