#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

if [[ -z "${username:-}" ]]; then
    display_name="$name"
    ynh_app_setting_set --key="display_name" --value="$display_name"
fi


# migrating from microblog_ynh package version v1 from sr.ht
if [[ $(ynh_app_setting_get --key='installed_from') != 'YunohostV2catalogVersion' ]]; then
    # rename microblogpub/microblogpub to microblogpub/app
	ynh_script_progression "upgrade from package-format v1: renaming app directory"
    mv "/var/www/${app}/microblogpub" "/var/www/${app}/app"

    # remove old .pyenv pyenv and venv directories
	ynh_script_progression "upgrade from package-format v1: removing old python env"
    ynh_safe_rm "/var/www/${app}/.pyenv"

    ynh_safe_rm "/var/www/${app}/pyenv"

    ynh_safe_rm "/var/www/${app}/venv"

	ynh_script_progression "upgrade from package-format v1: move data to $data_dir"
    microblogpub_move_data

    ynh_script_progression "Mark this as updated to V2 app integration..."
    ynh_app_setting_set --key='installed_from' --value='YunohostV2catalogVersion'
fi

### This helper will compare the version of the currently installed app and the version of the upstream package.
### $upgrade_type can have 2 different values
### - UPGRADE_APP if the upstream app version has changed
### - UPGRADE_PACKAGE if only the YunoHost package has changed
### ynh_check_app_version_changed will stop the upgrade if the app is up to date.
### UPGRADE_APP should be used to upgrade the core app only if there's an upgrade to do.

ynh_print_info "

ynh_script_progression "Stopping $app's systemd service..."
ynh_systemctl --service=$app --action="stop"

ynh_config_add --template="inv.sh" --destination="$install_dir/inv.sh"
chmod u+x $install_dir/inv.sh

# FIXME: this is still supported but the recommendation is now to *always* re-setup the app sources wether or not the upstream sources changed
if ynh_app_upstream_version_changed; then
	ynh_script_progression "Upgrading python to $python_version..."
    microblogpub_install_python

	ynh_script_progression "Upgrading source files..."
	# ynh_setup_source --dest_dir="${microblogpub_app}"  --keep="data"
    # after extracting the new version there's a new directory ./data that can't
    # be overwritten by ynh_setup_source with the symlink it backed up
    # WARNING cp: cannot overwrite directory '/var/www/microblogpub/app/data' with non-directory
    # this is the reason, why we just overwrite the source and then restore the
    # symlink
    ynh_setup_source --dest_dir="${microblogpub_app}"
    microblogpub_move_data

	ynh_script_progression "Upgrading dependencies..."
    microblogpub_install_deps

	ynh_script_progression "Getting venv path..."
    microblogpub_set_active_venv

    ynh_script_progression "Running microblog.pub update script..."
    microblogpub_update

    ynh_script_progression "Setting yunohost version to be shown on page..."
    microblogpub_set_version
fi

ynh_script_progression "Setting file permissions..."
microblogpub_set_filepermissions

ynh_script_progression "Upgrading NGINX web server configuration..."
ynh_config_add_nginx

ynh_script_progression "Upgrading systemd configuration..."
ynh_config_add_systemd

ynh_script_progression "Upgrading logrotate configuration..."
ynh_config_add_logrotate

ynh_script_progression "Integrating service in YunoHost..."
yunohost service add $app --description="A self-hosted, single-user, ActivityPub powered microblog." --log="/var/log/$app/$app.log"

ynh_script_progression "Starting $app's systemd service..."
ynh_systemctl --service=$app --action="start"

ynh_script_progression "Upgrade of $app completed"
