#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

### This helper will compare the version of the currently installed app and the version of the upstream package.
### $upgrade_type can have 2 different values
### - UPGRADE_APP if the upstream app version has changed
### - UPGRADE_PACKAGE if only the YunoHost package has changed
### ynh_check_app_version_changed will stop the upgrade if the app is up to date.
### UPGRADE_APP should be used to upgrade the core app only if there's an upgrade to do.
upgrade_type=$(ynh_check_app_version_changed)
ynh_print_info --message="upgrade_type=${upgrade_type}"

ynh_script_progression --message="Stopping a systemd service..." --weight=1
ynh_systemd_action --service_name=$app --action="stop" --log_path="/var/log/$app/$app.log"

ynh_add_config --template="inv.sh" --destination="$install_dir/inv.sh"
chmod u+x $install_dir/inv.sh

if [ "$upgrade_type" == "UPGRADE_PACKAGE" ]; then
    microblogpub_install_python
    microblogpub_install_deps
fi

if [ "$upgrade_type" == "UPGRADE_APP" ]; then
	ynh_script_progression --message="Upgrading python to $python_version..." --weight=1
    microblogpub_install_python

	ynh_script_progression --message="Upgrading source files..." --weight=1
	ynh_setup_source --dest_dir="${microblogpub_app}"  --keep="data/"

	ynh_script_progression --message="Upgrading dependencies..." --weight=1
    microblogpub_install_deps

	ynh_script_progression --message="Getting venv path..." --weight=1
    microblogpub_set_active_venv

    ynh_script_progression --message="Running microblog.pub update script..." --weight=1
    microblogpub_update
fi

ynh_script_progression --message="Setting yunohost version to be shown on page..." --weight=1
microblogpub_set_version

ynh_script_progression --message="Setting file permissions..." --weight=1
microblogpub_set_filepermissions

ynh_script_progression --message="Upgrading NGINX web server configuration..." --weight=1
ynh_add_nginx_config

ynh_script_progression --message="Upgrading systemd configuration..." --weight=1
ynh_add_systemd_config

ynh_script_progression --message="Upgrading logrotate configuration..." --weight=1
ynh_use_logrotate --non-append

ynh_script_progression --message="Integrating service in YunoHost..." --weight=1
yunohost service add $app --description="A self-hosted, single-user, ActivityPub powered microblog." --log="/var/log/$app/$app.log"

ynh_script_progression --message="Starting a systemd service..." --weight=1
ynh_systemd_action --service_name=$app --action="start" --log_path="/var/log/$app/$app.log"

ynh_script_progression --message="Upgrade of $app completed" --last
